services:
  - type: web
    name: voice-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn voice_agent:app --host 0.0.0.0 --port 10000
    envVars:
      - key: AIzaSyBh-gQTCd4NrtSeO534KM8FznaMdDwXI94
        value: /etc/secrets/tts-credentials.json
    secretFiles:
      - path: /etc/secrets/tts-credentials.json
        contents: <your-service-account-json>
